-- MySQL Script generated by MySQL Workbench
-- Mon Jul 16 21:50:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET latin1 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`sub_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`sub_categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `descricao` VARCHAR(999) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `id_imgs` VARCHAR(999) NULL DEFAULT NULL,
  `drescicao` VARCHAR(9999) NULL DEFAULT NULL,
  `subcategoria_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategoria_id` (`subcategoria_id` ASC),
  CONSTRAINT `categorias_ibfk_1`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `ecommerce`.`sub_categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`ufs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ufs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `DDD` TINYINT(2) NULL DEFAULT NULL,
  `UFs` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `UFs` (`UFs` ASC),
  CONSTRAINT `cidades_ibfk_1`
    FOREIGN KEY (`UFs`)
    REFERENCES `ecommerce`.`ufs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `sobrenome` VARCHAR(30) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` TINYINT(10) UNSIGNED NULL DEFAULT NULL,
  `celular` TINYINT(11) UNSIGNED NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `email_recup` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `cpf` TINYINT(50) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `numero` TINYINT(5) NOT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `CEP` TINYINT(10) NOT NULL,
  `cidades_fk` INT(11) NULL DEFAULT NULL,
  `uf_fk` INT(11) NULL DEFAULT NULL,
  `favoritos_fk` INT(11) NULL DEFAULT NULL,
  `historico_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `email_recup` (`email_recup` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  INDEX `cidades_fk` (`cidades_fk` ASC),
  INDEX `uf_fk` (`uf_fk` ASC),
  INDEX `favoritos_fk` (`favoritos_fk` ASC),
  INDEX `historico_id` (`historico_id` ASC),
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`cidades_fk`)
    REFERENCES `ecommerce`.`cidades` (`id`),
  CONSTRAINT `usuarios_ibfk_2`
    FOREIGN KEY (`uf_fk`)
    REFERENCES `ecommerce`.`ufs` (`id`),
  CONSTRAINT `usuarios_ibfk_3`
    FOREIGN KEY (`favoritos_fk`)
    REFERENCES `ecommerce`.`favoritos` (`id`),
  CONSTRAINT `usuarios_ibfk_4`
    FOREIGN KEY (`historico_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`marcas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `descricao` VARCHAR(999) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cor` VARCHAR(50) NULL DEFAULT NULL,
  `tamanho` VARCHAR(50) NULL DEFAULT NULL,
  `preco` DECIMAL(6,2) NULL DEFAULT NULL,
  `estoque` TINYINT(3) NULL DEFAULT NULL,
  `id_imgs` VARCHAR(999) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(9999) NULL DEFAULT NULL,
  `categoria_fk` INT(11) NULL DEFAULT NULL,
  `subcategoria_fk` INT(11) NULL DEFAULT NULL,
  `marcas_fk` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_fk` (`categoria_fk` ASC),
  INDEX `subcategoria_fk` (`subcategoria_fk` ASC),
  INDEX `marcas_fk` (`marcas_fk` ASC),
  CONSTRAINT `produto_ibfk_1`
    FOREIGN KEY (`categoria_fk`)
    REFERENCES `ecommerce`.`categorias` (`id`),
  CONSTRAINT `produto_ibfk_2`
    FOREIGN KEY (`subcategoria_fk`)
    REFERENCES `ecommerce`.`sub_categoria` (`id`),
  CONSTRAINT `produto_ibfk_3`
    FOREIGN KEY (`marcas_fk`)
    REFERENCES `ecommerce`.`marcas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`favoritos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `produtos_fk` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `produtos_fk` (`produtos_fk` ASC),
  CONSTRAINT `favoritos_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`),
  CONSTRAINT `favoritos_ibfk_2`
    FOREIGN KEY (`produtos_fk`)
    REFERENCES `ecommerce`.`produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecommerce`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`historico` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `horario_compra` DATETIME NULL DEFAULT NULL,
  `id_pagamento` INT(11) NULL DEFAULT NULL,
  `status_pagamento` VARCHAR(50) NULL DEFAULT NULL,
  `produtos_id` INT(11) NULL DEFAULT NULL,
  `valor` DECIMAL(6,2) NULL DEFAULT NULL,
  `desconto` DECIMAL(6,2) NULL DEFAULT NULL,
  `cupom` VARCHAR(50) NULL DEFAULT NULL,
  `valor_final` DECIMAL(6,2) NULL DEFAULT NULL,
  `codigo_acompanhamento` VARCHAR(50) NULL DEFAULT NULL,
  `frete` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `produtos_id` (`produtos_id` ASC),
  CONSTRAINT `historico_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`),
  CONSTRAINT `historico_ibfk_2`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `ecommerce`.`produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
